{{- if .Values.server.ingressRoute.enabled }}
{{- $serviceName := include "vault.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $serviceName }}
  annotations:
    {{- toYaml .Values.server.ingressRoute.annotations | nindent 4 }}
spec:
  entryPoints:
    {{- range .Values.server.ingressRoute.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    {{- range .Values.server.ingressRoute.matchRules }}
    - match: Host(`{{ .host }}`)
      kind: {{ .kind }}
      services:
        - name: {{ .serviceName }}
          port: {{ .servicePort }}
      {{- with $.Values.server.ingressRoute.middlewares }}
      middlewares:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
  {{- with .Values.server.ingressRoute.tls }}
  tls:
    secretName: {{ .secretName }}
  {{- end }}
{{- end }}