---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-anundsson-net
  namespace: default
spec:
  secretName: local-anundsson-net-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.local.anundsson.net"
  dnsNames:
  - "local.anundsson.net"
  - "*.local.anundsson.net"