---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-anundsson-net-production
  namespace: default
spec:
  secretName: local-anundsson-net-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.anundsson.net"
  dnsNames:
  - "local.anundsson.net"
  - "*.local.anundsson.net"
