---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-anundsson-net
  namespace: default
spec:
  secretName: local-anundsson-net-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.anundsson.net"
  dnsNames:
  - "anundsson.net"
  - "*.anundsson.net"